CREATE TABLE person (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(20) NOT NULL UNIQUE,
                        password VARCHAR NOT NULL,
                        role VARCHAR(20) NOT NULL
);

CREATE TABLE task (
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      description TEXT,
                      created_at TIMESTAMP NOT NULL,
                      status VARCHAR(20) NOT NULL,
                      priority VARCHAR(20) NOT NULL,
                      person_id INT NOT NULL,

                      CONSTRAINT fk_task_person FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE
);